# For local testing, run:
# bundle exec jekyll serve --config _config.yml,_config-dev.yml
url: https://dev.sylvainmetayer.fr

isso:
    url: https://comments.sylvainmetayer.fr/dev/
    script: https://comments.sylvainmetayer.fr/dev/js/embed.min.js

show_drafts: true